name: 'Framelix Release Creator'
description: 'Create a release for a Framelix based project'
inputs:
  repo-token:
    description: 'Access token'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'